### PR TITLE
Fix username validation

### LINKED ISSUE #16: fix nickname validation
to be fixed on master for EF2021

the current implementation of nickname validation using a regexp is imprecise. The exact rule is: 
- the nickname must be trimmed
- it needs to contain at least one alphabetic character (unicode Letter or Digit)
- it must not contain more than 2 non-alphabetic characters (not counting spaces)

```
        int countAlpha = 0;
        int countNonAlpha = 0;

        int numUnits = t.length();

        for (int i = 0; i < numUnits; i++) {
            char c = t.charAt(i);

            if (Character.isLetterOrDigit(c)) {
                countAlpha++;
            } else if (' ' == c) {
                // blanks do not count for non-alphabetics
            } else {
                countNonAlpha++;
            }
        }

        if (countAlpha < 1) {
            String output = String.format(Strings.attendee.invalidNick, t);
            throw new DbDataException(output);
        }

        if (countNonAlpha > 2) {
            String output = String.format(Strings.attendee.invalidNickNonAlph, t);
            throw new DbDataException(output);
        }
```

### PR DESCRIPTION
**Pull request by ErikMelton**
Fixes #16

Improves validation by simplifying regex to 2 very simple expressions, as well as adding trim support and character count limits.

### CODE REVIEW

File: js/form.js [hunk 1]
```diff
@@ -269,12 +269,20 @@ function setupBirthday(limits) {
...
+
       return (
         value.length >= 1 &&
         value.length <= 80 &&
-        /^([A-Za-z0-9 ]*[A-Za-z0-9][A-Za-z0-9 ]*[^A-Za-z0-9 ]?[A-Za-z0-9 ]*[^A-Za-z0-9 ]?[A-Za-z0-9 ]*|[A-Za-z0-9 ]*[^A-Za-z0-9 ]?[A-Za-z0-9 ]*[A-Za-z0-9][A-Za-z0-9 ]*[^A-Za-z0-9 ]?[A-Za-z0-9 ]*|[A-Za-z0-9 ]*[^A-Za-z0-9 ]?[A-Za-z0-9 ]*[^A-Za-z0-9 ]?[A-Za-z0-9 ]*[A-Za-z0-9][A-Za-z0-9 ]*)$/.test(
-          value
-        )
+        value.trim() === value &&
+        numberSpecialCharacters <= 2 &&
+        /^[a-zA-Z0-9\u00c0-\u017e\u0400-\u04FF ]+$/.test(nameWithoutSpecialCharacters)
```
Comment (angryzor) [inline js/form.js:285]: I'm also not sure what you're testing here. Since you removed the special characters earlier with the inverse RegExp it seems logical that this would always be true. Am I missing something?

File: js/form.js [hunk 2]
```diff
@@ -269,12 +269,20 @@ function setupBirthday(limits) {
 function isValid(element, value) {
   switch (element) {
     case "nickname":
+      let numberSpecialCharacters = 0
+      let nameWithoutSpecialCharacters = ''
+
+      for (let i = 0; i < value.length; i++) {
+        if (/[^a-zA-Z0-9\u00c0-\u017e\u0400-\u04FF ]/.test(value[i])) numberSpecialCharacters++
```
Comment (Jumpy-Squirrel) [inline js/form.js:276]: It might make the check at the end more readable if you do something like
if (...) 
  numberSpecialCharacters++ 
elseif (... === " ") 
  numberSpaces++ 
else 
  numberRegularCharacters++

File: js/form.js (hunk 1 above)
Comment (Jumpy-Squirrel) [reply js/form.js:285]: Should we centralize the validation function into a single js file? It's kind of ugly to have it in two places in the code imho. I'd be fine with adding an extra .js file just for validations that is loaded in both the form and the submit page.

Comment (ErikMelton) [reply js/form.js:285]: It tests to ensure that there are no Leading or Trailing whitespace characters, and that we have two or fewer special characters, as required by the server. We then test to ensure that remaining characters include at least one "regular" character.

I think moving validation to a single js file would be the best scenario. I'll include that in this PR. :)
